version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: pontoDB
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345

    ports:
      - "3308:3306"